name: Usage Test
permissions: read-all

on:
  workflow_dispatch:
  merge_group:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DEBIAN_FRONTEND: noninteractive
  CMAKE_GENERATOR: Ninja
  USER_CMAKE_VERSION: 3.25

jobs:
  usage_test:
    runs-on: ${{ github.repository_owner == 'intel' && 'intel-' || '' }}ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        cpp_implementation: [FREESTANDING, HOSTED]
        compiler: [clang, gcc]
        include:
          - compiler: clang
            cc: "clang"
            cxx: "clang++"
            install: sudo apt update && sudo apt install -y clang-18
            toolchain_root: "/usr/lib/llvm-18"
          - compiler: gcc
            cc: "gcc-12"
            cxx: "g++-12"
            install: sudo apt update && sudo apt install -y gcc-12 g++-12
            toolchain_root: "/usr"

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Install compiler
        run: |
          ${{ matrix.install }}
          sudo apt install -y ninja-build

      - name: Install cmake
        run: |
          python3 -m venv ${{github.workspace}}/test_venv
          source ${{github.workspace}}/test_venv/bin/activate
          pip install cmake==${{env.USER_CMAKE_VERSION}}

      - name: Configure cmake
        env:
          CC: ${{matrix.toolchain_root}}/bin/${{matrix.cc}}
          CXX: ${{matrix.toolchain_root}}/bin/${{matrix.cxx}}
        working-directory: ${{github.workspace}}/usage_test
        run: ${{github.workspace}}/test_venv/bin/cmake -B build -DCPP_IMPLEMENTATION=${{matrix.cpp_implementation}}

      - name: Build
        working-directory: ${{github.workspace}}/usage_test
        run: ${{github.workspace}}/test_venv/bin/cmake --build build
